---
miners:
  - ip: 192.168.0.113
    name: antminer-s9-se-t17-001
    user: root # Overwrites global credentials for this miner
    password: root # Overwrites global credentials for this miner

# Global credentials, if you have the same for all miners
credentials:
  user: root
  password: root